### ISSUE TITLE
missing sl.lidar.h

### ISSUE THREAD

**Issue by joshuahhn** [Ajasra/SlamtecCHOP#3]
I do all the step setup the linking.

https://github.com/Slamtec/rplidar_sdk/issues/71#issuecomment-1382005055

However it still keep saying "C1083 'sl_lidar.h': No such file or directory"

Because I am trying the C1 , I have to build the new dll. ( and V3 is not support. )

**Comment by Nullifier** [comment]
I'm getting the same erorr when compiling. Trying to use it with C1
